
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/calculator_schema
    username: root
    password: zemoso123
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true